Add "dev_parallel" mode and avoid root sudo in test script

diff --git a/core_utils/mediawiki-phpunit b/core_utils/mediawiki-phpunit
--- a/core_utils/mediawiki-phpunit
+++ b/core_utils/mediawiki-phpunit
@@ -1,50 +1,32 @@
 #!/usr/bin/env bash
 
 WSL_CORE="/srv/mediawiki/core"
-BASE_DIR=$(dirname $(realpath $0))
-SCRIPT_BASENAME=$(basename "$(realpath "$0")")
+REAL_PATH=$(realpath "$0")
+BASE_DIR=$(dirname "$REAL_PATH")
+SCRIPT_BASENAME=$(basename "$REAL_PATH")
+TMP_SUBDIR_NAME="mediawiki-phpunit"
 
-OPERATION=$1
+COMMAND=$1
 shift 1
-ARGS="$@"
+declare -a ARGS=("$@")
 
 function print_usage() {
     echo "Usage: ${SCRIPT_BASENAME} <dev|srv|srv_parallel>"
 }
 
-function check_working_dir_is_clean() {
-    local CHANGES
-
-    CHANGES=$(git diff --name-status)
-    [ $? -eq 0 ] || exit $?
-
-    if [ -n "${CHANGES}" ]; then
-        echo -e "Uncommitted changes in {$PWD}:\n${CHANGES}" >&2
-        exit 1
-    fi
-
-    exit 0
-}
-
 function prepare_tmpfs_temp_dir() {
-    TMPFS_DIR=$1
+    local TMPDIR_MOUNT=$1
+    local TMPDIR_MEDIAWIKI="${TMPDIR_MOUNT}/${TMP_SUBDIR_NAME}"
 
-    if [ -z "${TMPFS_DIR}" ]; then
-        echo "Missing temp directory mount path" >&2
+    if [ ! -d "${TMPDIR_MOUNT}" ]; then
+        echo "Invalid temp file mount path: ${TMPDIR_MOUNT}" >&2
         exit 127
     fi
 
-    if [ -d "${TMPFS_DIR}" ]; then
-        if grep -qs " ${TMPFS_DIR} " /proc/mounts; then
-            echo -n "Clearing tmpfs mount at '${TMPFS_DIR}'..." || exit 1
-            sudo -u www-data -H rm -rf "${TMPFS_DIR}/*" || exit 1
-        else
-            echo -n "Mounting tmpfs at '${TMPFS_DIR}'..."
-            sudo mount -t tmpfs -o size=256m tmpfs "${TMPFS_DIR}" || exit 1
-        fi
-		sudo chown www-data:www-data "${TMPFS_DIR}" || exit 1
-		echo "done"
-    fi
+	echo -n "Clearing '${TMPDIR_MEDIAWIKI}'..."
+	sudo -u www-data mkdir -p "${TMPDIR_MEDIAWIKI}"
+	sudo -u www-data -H rm -rf "${TMPDIR_MEDIAWIKI}/*" || exit $?
+	echo "done"
 }
 
 function sync_wsl_mediawiki_dir() {
@@ -56,8 +38,10 @@ function execute_mediawiki_phpunit() {
     local MEDIAWIKI_DIR=$1
     local TMPFS_DIR=$2
     (
-        cd "$MEDIAWIKI_DIR" || exit 1
-        exec sudo TMPDIR="${TMPFS_DIR}" -u www-data \
+    	set -e
+
+        cd "$MEDIAWIKI_DIR"
+        exec sudo TMPDIR="${TMPFS_DIR}" -u www-data -H \
             php "./tests/phpunit/phpunit.php" --colors=always "${ARGS[@]}" 2>&1
     )
 }
@@ -67,8 +51,8 @@ function execute_mediawiki_paratest() {
     local TMPFS_DIR=$2
     local PHP_ARGS=""
 
-	if [ -w /opcache/php ]; then
-		echo "Using shared OPCache directory /opcache/php"
+	if [ -d /opcache/php ]; then
+		echo "Using shared OPCache directory: /opcache/php"
 		PHP_ARGS+=" -d opcache.enable=1"
 		PHP_ARGS+=" -d opcache.enable_cli=1"
 		PHP_ARGS+=" -d opcache.file_cache=/opcache/php"
@@ -76,10 +60,12 @@ function execute_mediawiki_paratest() {
 	fi
 
     (
-        cd "$MEDIAWIKI_DIR" || exit 1
+    	set -e
+
+        cd "$MEDIAWIKI_DIR"
         # XXX: ugly work-around poorly divided suites
-        sudo -u www-data -H cp "${BASE_DIR}/../config/mw_core_suite.xml" "./tests/phpunit/" || exit 1
-        sudo -u www-data -H cp "${BASE_DIR}/../config/ParatestWrapperSettings.php" "./" || exit 1
+        sudo -u www-data -H cp "${BASE_DIR}/../config/mw_core_suite.xml" "./tests/phpunit/"
+        sudo -u www-data -H cp "${BASE_DIR}/../config/ParatestWrapperSettings.php" "./"
         exec sudo TMPDIR="${TMPFS_DIR}" -u www-data -H paratest \
             --phpunit tests/phpunit/phpunit.php \
             --configuration tests/phpunit/mw_core_suite.xml \
@@ -88,28 +74,42 @@ function execute_mediawiki_paratest() {
             --runner Runner \
             --colors \
             --passthru-php="${PHP_ARGS}" \
-            --passthru="--conf ParatestWrapperSettings.php --colors=always ${ARGS[@]}" 2>&1
+            --passthru="--conf ParatestWrapperSettings.php --colors=always ${ARGS[*]}" 2>&1
     )
 }
 
-case $OPERATION in
+# Try to use a tmpfs for temporary test files
+if [ "$(findmnt -no fstype -T /tmp 2>/dev/null)" == "tmpfs" ]; then
+	TMPDIR_MOUNT="/tmp"
+elif [ "$(findmnt -no fstype -T /run/shm 2>/dev/null)" == "tmpfs" ]; then
+	TMPDIR_MOUNT="/run/shm"
+else
+	TMPDIR_MOUNT="/tmp"
+	echo "Temporary directory is not a tmpfs; tests might be slow" >&2
+fi
+
+# Note that the "development path" just means $PWD
+case $COMMAND in
 "dev" | "")
-    # The development path can belong to WIN10 or Linux; just use $PWD
-    prepare_tmpfs_temp_dir "/mw-temp" || exit $?
-    execute_mediawiki_phpunit . "/mw-temp" | less -R
+    prepare_tmpfs_temp_dir "${TMPDIR_MOUNT}" || exit $?
+    execute_mediawiki_phpunit . "${TMPDIR_MOUNT}" | less -R
+    ;;
+"dev_parallel")
+    prepare_tmpfs_temp_dir "${TMPDIR_MOUNT}" || exit $?
+    execute_mediawiki_paratest . "${TMPDIR_MOUNT}" | less -R
     ;;
 "srv")
     sync_wsl_mediawiki_dir || exit $?
-    prepare_tmpfs_temp_dir "/mw-temp" || exit $?
-    execute_mediawiki_phpunit "${WSL_CORE}" "/mw-temp" | less -R
+    prepare_tmpfs_temp_dir "${TMPDIR_MOUNT}" || exit $?
+    execute_mediawiki_phpunit "${WSL_CORE}" "${TMPDIR_MOUNT}" | less -R
     ;;
 "srv_parallel")
     sync_wsl_mediawiki_dir || exit $?
-    prepare_tmpfs_temp_dir "/mw-temp" || exit $?
-    execute_mediawiki_paratest "${WSL_CORE}" "/mw-temp" | less -R
+    prepare_tmpfs_temp_dir "${TMPDIR_MOUNT}" || exit $?
+    execute_mediawiki_paratest "${WSL_CORE}" "${TMPDIR_MOUNT}" | less -R
     ;;
 *)
-    echo "Invalid command: ${OPERATION}" >&2
+    echo "Invalid command: ${COMMAND}" >&2
     print_usage
     exit 127
     ;;
